server:
  port: 8001
spring:
  application:
    name: auth-service
  cloud:
    nacos:
      server-addr: localhost:8848
    openfeign:
      okhttp:
        enabled: true
feign:
  sentinel:
    # 必须引入sentinel并开启这个才可以触发兜底
    enabled: true
