server:
  port: 8080
  max-http-request-header-size: 40KB
  tomcat:
    max-http-response-header-size: 40KB

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848

    gateway:
      httpclient:
        max-initial-line-length: 40KB
        max-header-size: 40KB

      routes:
        - id: auth-service # 路由规则id，自定义，唯一
          uri: lb://auth-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/auth/** # 这里是以请求路径作为判断规则
        - id: sys-service
          uri: lb://sys-service
          predicates:
            - Path=/sys/**
        - id: msg-service
          uri: lb://msg-service
          predicates:
            - Path=/msg/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=/location/**
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stock/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**