server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848

    gateway:
      routes:
        - id: auth-service # 路由规则id，自定义，唯一
          uri: lb://auth-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/auth/** # 这里是以请求路径作为判断规则
        - id: sys-service
          uri: lb://sys-service
          predicates:
            - Path=/sys/**
        - id: msg-service
          uri: lb://msg-service
          predicates:
            - Path=/msg/**