server:
  port: 8004

spring:
  application:
    name: product-service
  cloud:
    nacos:
      server-addr: localhost:8848
    openfeign:
      okhttp:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

feign:
  sentinel:
    # 必须引入sentinel并开启这个才可以触发兜底
    enabled: true

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-server
      username: nacos
      password: nacos
  tx-service-group: wms
  service:
    vgroup-mapping:
      wms: "default"